force-app/main/default/objects/Account/fields/Base_Title__c.field-meta.xml
<CustomField>
    <fullName>Base_Title__c</fullName>
    <label>Base Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Publisher</fullName>
            </value>
            <value>
                <fullName>Developer/Publisher</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PlayStation_4__c.field-meta.xml
<CustomField>
    <fullName>PlayStation_4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PlayStation 4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Base_Title__c.field-meta.xml
<CustomField>
    <fullName>Base_Title__c</fullName>
    <description>This is the name that will appear on the PlayStation Storefront</description>
    <label>Base Title</label>
    <length>62</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PS3</fullName>
            </value>
            <value>
                <fullName>PS4</fullName>
            </value>
            <value>
                <fullName>PSM</fullName>
            </value>
            <value>
                <fullName>PSVita</fullName>
            </value>
            <value>
                <fullName>PlayStation TV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>Platform_Type__c</fullName>
    <label>Platform Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PlayStation®4</fullName>
            </value>
            <value>
                <fullName>PlayStation®Vita</fullName>
            </value>
            <value>
                <fullName>PlayStation®3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityManagementTest.cls
public with sharing class OpportunityManagementTest {
    
    static testMethod void updatePlatformRecord_Test() {
        OpportunityManagement op = new OpportunityManagement();
    }
    
   /* static testMethod void updatePlatformRecord_Test() {
    List<Account> accList = new List<Account>();
    Account acc = new Account();
    acc.Name = 'Polo Inc';
    acc.Business_Type__c = 'Developer/Publisher';
    acc.PlayStation_3__c =  true;
    acc.PlayStation_4__c = true;
    acc.PlayStation_Vita__c = false;
    accList.add(acc);
    
    insert accList;
    
    
    
    
    Opportunity opp = new Opportunity();
    opp.Name = acc.Name + 'PS3';
    opp.Description  = 'Test opportunity';
    opp.Account = acc;
    opp.Base_Title__C = 'Test Base title';
    opp.Platform_Type__c = 'PlayStation®3';
    opp.CloseDate =  date.today().addDays(150);
    opp.StageName= 'Technical Evaluation';
    insert opp;
    
        
    List<opportunity> oppList = new List<opportunity>();
    oppList.add(opp);
    OpportunityManagement.afterOpportunityInsert(oppList); 
      
       
    /*List<Platform__c> platformList = [select Id,Platform_Type__c,Name, Opportunity__c 
                                      from Platform__c
                                      where Account__c = :acc.Id];*/
                                  
                                      
                                    
    
 /* }*/

}