force-app/main/default/objects/Opportunity/fields/AdSales_CF_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>AdSales_CF_Start_Date__c</fullName>
    <inlineHelpText>Date when campaign is expected to start.</inlineHelpText>
    <label>Opportunity Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ProductControllerTest.cls
@isTest
public class ProductControllerTest {
    Static testMethod void testOpportunityLineItemList(){
        ProductController pc = new ProductController();
        
        /*list<OpportunityLineItem> oppLine = new List<OpportunityLineItem>();
        List<Product2> products = new List<Product2>();
        
        Account acc = new Account(Name = 'Test');
        insert acc;
        
        //Opportunity opp = new Opportunity (Name = 'OPP',StageName = 'Opportunity Created',CloseDate = date.Today() + 30,AccountID =acc.Id);
		//insert opp;
        
        for (Integer count = 0; count < 5; count++) {
            products.add(new Product2 (Name = 'Feature'+count,IsActive=true));
        }
        insert products;
        
		Product2 productItem = [Select Id,Name from Product2 Limit 1];

        PricebookEntry price = new PricebookEntry(UseStandardPrice = false,Pricebook2Id = Test.getStandardPricebookId(),UnitPrice = 1.0, IsActive = true,Product2Id = productItem.Id);
		insert price;
		
		Opportunity opp = new Opportunity (Name = 'OPP', Pricebook2Id = Test.getStandardPricebookId(),StageName = 'Opportunity Created',CloseDate = date.Today() + 30,AccountID =acc.Id);
		insert opp;

        //Opportunity oppItem = [Select Id,Name,StageName from Opportunity Limit 1];
        for(Integer count = 0; count < 3; count++){
            oppLine.add(new OpportunityLineItem (OpportunityId = opp.Id,Quantity = 1.0,AdSales_CF_Start_Date__c= date.Today(),AdSales_CF_End_Date__c = date.Today() + 2,TotalPrice = 1.0,PricebookEntryId = price.Id));
        }
        
        insert oppLine;
        Test.startTest();
        ProductController.getTasks();
        Test.stopTest();*/
    }

}