force-app/main/default/objects/Opportunity/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PS3</fullName>
            </value>
            <value>
                <fullName>PS4</fullName>
            </value>
            <value>
                <fullName>PSM</fullName>
            </value>
            <value>
                <fullName>PSVita</fullName>
            </value>
            <value>
                <fullName>PlayStation TV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>Platform_Type__c</fullName>
    <label>Platform Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PlayStation®4</fullName>
            </value>
            <value>
                <fullName>PlayStation®Vita</fullName>
            </value>
            <value>
                <fullName>PlayStation®3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityManagement.cls
public class OpportunityManagement {
public OpportunityManagement (){}
 /* public static void afterOpportunityInsert (List<Opportunity> opptyList) {
    updatePlatform(opptyList);
  }
  public static void updatePlatform (List<Opportunity> opptyList) {
    Set<Id> accountIdSet = new Set<Id>();
    for (Opportunity opp : opptyList) {
      accountIdSet.add(opp.AccountId);
    }
    List<Platform__c> pltformListUpdate = new List<Platform__c>();
    List<Platform__c> pltformList = [select Id, Platform_Type__c, Account__c 
                                     from Platform__c
                                     where Account__c in :accountIdSet];
    for (Opportunity opp : opptyList) {
      for(Platform__c pltfrm : pltformList) {       
        if (opp.Platform_Type__c == pltfrm.Platform_Type__c 
          && opp.AccountId == pltfrm.Account__c) {
          pltfrm.Opportunity__c = opp.Id;
          pltformListUpdate.add(pltfrm);
        }
      }
    }
    Database.update(pltformListUpdate);
  }*/
}